name: Build Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v5.3

    steps:
    - uses: actions/checkout@v3

    - name: Build basic_capture example
      run: |
        . $IDF_PATH/export.sh
        cd examples/basic_capture
        idf.py set-target esp32p4
        idf.py build
